version: '2.2'
services:
  app:
    container_name: social-media-backend
    restart: always
    build: .
    ports:
      - '4000:4000'
    volumes:
      - .:/app/
      - /app/node_modules
    command: npm run start:production
